[2022-10-15 12:40:33,294] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2022-10-14T00:00:00+00:00 [queued]>
[2022-10-15 12:40:33,308] {taskinstance.py:896} INFO - Dependencies all met for <TaskInstance: assignment.task_zero 2022-10-14T00:00:00+00:00 [queued]>
[2022-10-15 12:40:33,308] {taskinstance.py:1087} INFO - 
--------------------------------------------------------------------------------
[2022-10-15 12:40:33,309] {taskinstance.py:1088} INFO - Starting attempt 1 of 3
[2022-10-15 12:40:33,309] {taskinstance.py:1089} INFO - 
--------------------------------------------------------------------------------
[2022-10-15 12:40:33,323] {taskinstance.py:1107} INFO - Executing <Task(BashOperator): task_zero> on 2022-10-14T00:00:00+00:00
[2022-10-15 12:40:33,328] {standard_task_runner.py:52} INFO - Started process 79 to run task
[2022-10-15 12:40:33,331] {standard_task_runner.py:76} INFO - Running: ['***', 'tasks', 'run', 'assignment', 'task_zero', '2022-10-14T00:00:00+00:00', '--job-id', '37', '--pool', 'default_pool', '--raw', '--subdir', 'DAGS_FOLDER/assignment.py', '--cfg-path', '/tmp/tmpedsgurw3', '--error-file', '/tmp/tmpltdatbtz']
[2022-10-15 12:40:33,332] {standard_task_runner.py:77} INFO - Job 37: Subtask task_zero
[2022-10-15 12:40:33,375] {logging_mixin.py:104} INFO - Running <TaskInstance: assignment.task_zero 2022-10-14T00:00:00+00:00 [running]> on host 444c7ff3fdda
[2022-10-15 12:40:33,428] {taskinstance.py:1302} INFO - Exporting the following env vars:
AIRFLOW_CTX_DAG_OWNER=***
AIRFLOW_CTX_DAG_ID=assignment
AIRFLOW_CTX_TASK_ID=task_zero
AIRFLOW_CTX_EXECUTION_DATE=2022-10-14T00:00:00+00:00
AIRFLOW_CTX_DAG_RUN_ID=scheduled__2022-10-14T00:00:00+00:00
[2022-10-15 12:40:33,430] {subprocess.py:52} INFO - Tmp dir root location: 
 /tmp
[2022-10-15 12:40:33,431] {subprocess.py:63} INFO - Running command: ['bash', '-c', 'pip install beautifulsoup4']
[2022-10-15 12:40:33,439] {subprocess.py:75} INFO - Output:
[2022-10-15 12:40:34,691] {subprocess.py:79} INFO - Defaulting to user installation because normal site-packages is not writeable
[2022-10-15 12:40:34,879] {subprocess.py:79} INFO - Requirement already satisfied: beautifulsoup4 in /home/***/.local/lib/python3.6/site-packages (4.11.1)
[2022-10-15 12:40:34,887] {subprocess.py:79} INFO - Requirement already satisfied: soupsieve>1.2 in /home/***/.local/lib/python3.6/site-packages (from beautifulsoup4) (2.3.2.post1)
[2022-10-15 12:40:43,443] {subprocess.py:83} INFO - Command exited with return code 0
[2022-10-15 12:40:43,519] {taskinstance.py:1211} INFO - Marking task as SUCCESS. dag_id=assignment, task_id=task_zero, execution_date=20221014T000000, start_date=20221015T124033, end_date=20221015T124043
[2022-10-15 12:40:43,590] {taskinstance.py:1265} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2022-10-15 12:40:43,628] {local_task_job.py:151} INFO - Task exited with return code 0
